test_that("manifest roundtrip", {
  td <- tempdir()
  p1 <- file.path(td, "a.csv"); p2 <- file.path(td, "b.csv")
  readr::write_csv(tibble::tibble(x=1), p1)
  readr::write_csv(tibble::tibble(y=2), p2)
  man <- atc_manifest(c(p1, p2))
  expect_equal(nrow(man), 2)
  out <- atc_write_manifest(c(p1, p2))
  expect_true(file.exists(out))
})
